In [1]:
import numpy as np

In [2]:
## Q1
arr1 = np.array([0,1,2,3,4,5])
arr1
arr1.dtype

dtype('int32')

In [3]:
## Q2.
arr2 = np.array([1.5, 2.6, 3.7])
arr2.dtype

dtype('float64')

In [4]:
## Q3.
arr3 = np.array([4+5j,2-5j,5+6j])
arr3.dtype

dtype('complex128')

In [5]:
## Q4.
arr4 = arr1.astype(np.float32)
arr4.dtype

dtype('float32')

In [6]:
## Q5.
arr5 = arr2.astype(np.float32)
arr5.dtype

dtype('float32')

In [7]:
## Q6.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3])
array_attributes(arr)


((3,), 3, dtype('int32'))

In [8]:
## Q7.
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3]])
array_dimension(arr)


2

In [9]:
## Q8.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes #nbytes = arr.itemsize * arr.size (4*3=12)

arr = np.array([1,2,3])
item_size_info(arr)

(4, 12)

In [10]:
## Q9.
def array_strides(arr):
    return arr.strides
# Strides: In NumPy, strides represent the number of bytes that need to be 
# skipped in memory to move to the next element along each dimension of the array. 

arr = np.array([1.5, 2.6, 3.7])
array_strides(arr)


(8,)

In [11]:
## Q10.
def shape_strides(arr):
    return arr.shape, arr.strides

arr = np.array([1, 2, 3])
shape_strides(arr)


((3,), (4,))

In [12]:
def shape_strides(arr):
    return arr.shape, arr.strides

arr = np.array([1.5, 2.6, 3.7])
shape_strides(arr)

((3,), (8,))

In [13]:
## Q11.
def create_zeros_array(n):
    arr = np.zeros(n)
    return arr

In [14]:
create_zeros_array(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
## Q12.
def create_ones_matrix(n):
    arr = np.ones(n)
    return arr

In [16]:
create_ones_matrix((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## Q13.
def generate_range_array(s1,s2,s3):
    arr = np.arange(s1,s2,s3)
    return arr

generate_range_array(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
## Q14.
def generate_linear_space(s1,s2,n):
    arr = np.linspace(s1,s2,n)
    return arr

generate_linear_space(1,5,12)

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [19]:
## Q15.
def  create_identity_matrix(n):
    arr = np.eye(n)
    return arr

create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
## Q16.
def list_convert(n):
    return np.array(n) 

list_convert([1,3,'arun','4j'])

array(['1', '3', 'arun', '4j'], dtype='<U11')

In [21]:
## Q17.
original_array = np.arange(10)
view_array = original_array.view()

print('Original Array',original_array)
print('View Array',view_array)

Original Array [0 1 2 3 4 5 6 7 8 9]
View Array [0 1 2 3 4 5 6 7 8 9]


In [22]:
view_array[0] = 99
print('Original Array after modification',original_array)
print('View Array after modification',view_array)

Original Array after modification [99  1  2  3  4  5  6  7  8  9]
View Array after modification [99  1  2  3  4  5  6  7  8  9]


In [23]:
## Q18.
def array_concatenate(n1,n2,axis):
    arr1 = np.array(n1)
    arr2 = np.array(n2)
    return np.concatenate((arr1,arr2),axis=axis)


In [24]:
array_concatenate([[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
array_concatenate([[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
## Q19.
arr1 = np.random.randint(0,10,(2,4))
arr2 = np.random.randint(10,20,(3,4))

concat = np.concatenate((arr1,arr2),axis=0)
concat

array([[ 2,  8,  6,  3],
       [ 4,  8,  6,  9],
       [15, 15, 17, 16],
       [12, 12, 15, 12],
       [19, 15, 14, 13]])

In [27]:
## Q20.
def stack_array(arr1,arr2):
    x = np.array(arr1)
    y = np.array(arr2)
    n1 = np.vstack((x,y))
    n2 = np.hstack((x,y))
    return n1,n2

stack_array([1,2,3,4],[5,6,7,8])

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([1, 2, 3, 4, 5, 6, 7, 8]))

In [28]:
## Q21
def specific_range(start,stop,step):
    return np.arange(start,stop+1,step)

In [29]:
specific_range(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
## Q22.
def equal_spaced(s1,s2,n):
    return np.linspace(start=s1,stop=s2,num=n)

In [31]:
equal_spaced(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [32]:
## Q23
def log_spaced_array(start,stop,num):
    return np.logspace(np.log10(start),np.log10(stop),num=num)

In [33]:
log_spaced_array(1,1000,5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [34]:
import pandas as pd
df = pd.DataFrame(np.random.randint(1,100,size=(5,3)))
df

0   1   2
0  17  81  30
1  40  28  48
2  99   7  46
3  31  69  77
4  54   6  31

In [35]:
## Q25
data = pd.DataFrame(np.random.uniform(-10, 10, size=(5, 3)))
data

0         1         2
0 -9.180356 -3.450849  4.825575
1 -3.151764 -8.805520 -4.710917
2 -4.913521  2.897944 -9.600398
3  4.590593  2.817094 -9.080356
4  7.987231  0.802316  6.178354

In [36]:
def replace_negative(df,col_name):
    df[col_name] = np.where(df[col_name] < 0 ,0,df[col_name])
    return df

In [37]:
replace_negative(data,1)

0         1         2
0 -9.180356  0.000000  4.825575
1 -3.151764  0.000000 -4.710917
2 -4.913521  2.897944 -9.600398
3  4.590593  2.817094 -9.080356
4  7.987231  0.802316  6.178354

In [38]:
## Q26.
arr  = np.array([10,20,30,40,50])
arr[2]

30

In [39]:
## Q27.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [40]:
arr_2d[1,2]

6

In [41]:
## Q28.
arr = np.array([3, 8, 2, 10, 5, 7])

In [42]:
arr[arr>5]

array([ 8, 10,  7])

In [43]:
## Q29.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [44]:
## Q30.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [45]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [46]:
## Q31.
def extract_element(arr,indices):
    indices = indices.astype(int)
    extract_element = arr[indices[:,0],indices[:,1]]
    return extract_element

In [47]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

indices = np.array([[0,1],
                    [1,2],
                    [2,0]])

extracted_element = extract_element(arr,indices)
extracted_element

array([20, 60, 70])

In [48]:
## Q32
def filter_elements(arr,n):
    arr = np.array(arr)
    filtered = arr[arr>n]
    return filtered
    

In [49]:
filter_elements([7,4,5,9,2,9,8],5)

array([7, 9, 9, 8])

In [50]:
## Q33.
def extract_element(arr,indices):
    indices = indices.astype(int)
    extract_element = arr[indices[:,0],indices[:,1],indices[:,2]]
    return extract_element

In [51]:
arr = np.array([[[10,20,30],
                 [40,50,60],
                 [70,80,90]],
                 
                [[100,110,120],
                 [130,140,150],
                 [160,170,180]],
                
                [[190,200,210],
                 [220,230,240],
                 [250,260,270]]])

indices = np.array([[[0,1,2],
                     [2,2,1],
                     [1,0,0]]])

extracted_element = extract_element(arr,indices)
extracted_element

array([[ 80, 160, 220]])

In [52]:
## Q34.
def check_condition(arr,cond1,cond2):
    arr = np.array(arr)
    check = cond1(arr) & cond2(arr)
    return arr[check]

In [53]:
def condition1(x):
    return x > 5

def condition2(x):
    return x %2 ==0

check_condition([1,2,3,4,5,6,7,8,9,10],condition1,condition2)

array([ 6,  8, 10])

In [54]:
## Q35.
def extract_element(arr,indices):
    indices = indices.astype(int)
    extract_element = arr[indices[:,0],indices[:,1]]
    return extract_element

In [55]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

indices = np.array([[0,1],
                    [1,2],
                    [2,0]])

extracted_element = extract_element(arr,indices)
extracted_element

array([20, 60, 70])

In [56]:
## Q36.
arr = np.random.randint(1,10,(3,3))
arr

array([[6, 1, 9],
       [4, 3, 8],
       [3, 3, 6]])

In [57]:
arr +5

array([[11,  6, 14],
       [ 9,  8, 13],
       [ 8,  8, 11]])

In [58]:
## Q37.
arr1 = np.random.randint(1,10,(1,3))
arr2 = np.random.randint(10,20,(3,4))
arr1,arr2

(array([[4, 8, 5]]),
 array([[12, 15, 18, 12],
        [13, 10, 18, 15],
        [12, 16, 15, 18]]))

In [59]:
arr1 = arr1.reshape(3,1)
result = arr2 * arr1
result

array([[ 48,  60,  72,  48],
       [104,  80, 144, 120],
       [ 60,  80,  75,  90]])

In [60]:
## Q38.
arr1 = np.random.randint(1,10,(1,4))
arr2 = np.random.randint(10,20,(4,3))
arr1,arr2

(array([[9, 5, 3, 9]]),
 array([[12, 15, 13],
        [10, 13, 13],
        [17, 19, 18],
        [12, 14, 18]]))

In [61]:
arr1 = arr1.reshape(4,1)
arr1 + arr2

array([[21, 24, 22],
       [15, 18, 18],
       [20, 22, 21],
       [21, 23, 27]])

In [62]:
## Q39.
arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(10,20,(1,3))
arr1,arr2

(array([[1],
        [6],
        [9]]),
 array([[19, 13, 10]]))

In [63]:
arr1 = arr1.reshape(1,3)
arr1 + arr2

array([[20, 19, 19]])

In [64]:
## Q40.
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(10,20,(2,2))
arr1,arr2

(array([[7, 6, 4],
        [9, 8, 6]]),
 array([[14, 11],
        [17, 18]]))

In [65]:
arr2_expand = np.hstack([arr2,arr2[:,-1:]])
arr2_expand

array([[14, 11, 11],
       [17, 18, 18]])

In [66]:
arr1 * arr2_expand

array([[ 98,  66,  44],
       [153, 144, 108]])

In [67]:
## Q41.
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [69]:
## Q42.
arr.max(axis=1)

array([3, 6])

In [70]:
## Q43.
arr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [71]:
## Q45.
arr = np.array([[2,4,6],[3,5,7]])
arr

array([[2, 4, 6],
       [3, 5, 7]])

In [72]:
arr[arr %2 == 0]

array([2, 4, 6])

In [73]:
## Q46.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [74]:
arr = original_array.reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
## Q47
def flatten_matrix(matrix):
    return matrix.flatten()

In [76]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flatten_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [77]:
## Q48.
def concat_arr(arr1,arr2,ax):
    return np.concatenate((arr1,arr2),axis=ax)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concat_arr(array1,array2,ax =0) ## Rowise

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [78]:
concat_arr(array1,array2,ax =1) # Columnwise

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [79]:
## Q49.
def split_array(arr, num_splits, axis):
    return np.split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = split_array(original_array, num_splits=3, axis=1)
sub_arrays

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [80]:
## Q50.
def modify_array(arr,insert_indices,insert_values,delete_indices):
    for index , value in zip(insert_indices,insert_values):
        arr = np.insert(arr,index,value)
        print(arr)

    arr = np.delete(arr,delete_indices)
    return arr

In [81]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
modify_array(arr=original_array,insert_indices=indices_to_insert,insert_values=values_to_insert,delete_indices=indices_to_delete)

[ 1  2 10  3  4  5]
[ 1  2 10  3 11  4  5]


array([ 1, 10, 11,  4,  5])

In [82]:
## Q51.
arr1 = np.random.randint(1, 1000 , 10)
arr2 = np.random.randint(1, 100, 10)
print("arr1:", arr1)
print("arr2:", arr2)
result = arr1 + arr2
print("result:",result)

arr1: [845 240 718 832 607 838 992 198 288  15]
arr2: [92 95 70 64 35 50 38 71 23 65]
result: [ 937  335  788  896  642  888 1030  269  311   80]


In [83]:
## Q52.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print("arr1:", arr1)
print("arr2:", arr2)
result = arr1 - arr2
print("result:",result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [84]:
## Q53.
arr1 = np.random.randint(10, 100 , 10)
arr2 = np.random.randint(1, 5, 10)
print("arr1:", arr1)
print("arr2:", arr2)
result = arr1 * arr2
print("result:",result)

arr1: [54 35 68 22 41 71 29 79 82 33]
arr2: [2 4 1 3 2 3 2 3 3 3]
result: [108 140  68  66  82 213  58 237 246  99]


In [85]:
## Q54.
arr1 = np.arange(2, 11, 2)
arr2 = np.random.randint(1, 5, 5)
print("arr1:", arr1)
print("arr2:", arr2)
result = arr1 / arr2
print("result",result)

arr1: [ 2  4  6  8 10]
arr2: [4 4 3 3 4]
result [0.5        1.         2.         2.66666667 2.5       ]


In [86]:
## Q55.
arr1 = np.random.randint(1,5,5)
arr2 = arr1[::-1]
print(arr1)
print(arr2)
result = arr1 ** arr2
print("result:",result)

[4 3 4 2 1]
[1 2 4 3 4]
result: [  4   9 256   8   1]


In [87]:
## Q56.
def occurance(arr,substring):
    count = 0
    for i in arr:
        if i == substring:
            count +=1

    return count

In [88]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurance(arr,substring)

3

In [89]:
## Q57.
def upper_case(arr):
    upper_char=[]
    for i in arr:
        for j in i:
            if j.isupper():
                upper_char.append(j)

    return upper_char

In [90]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
upper_case(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [91]:
## Q58.
def replace_string(arr,old_substring,new_substring):
    substring= np.array([i.replace(old_substring,new_substring) for i in arr])
    return substring

In [92]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replace_string(arr,'banana','fruit')

array(['apple', 'fruit', 'grape', 'pineapple'], dtype='<U9')

In [93]:
def replacing_string(arr,old,new):
    replaced_list = []
    for i in arr:
        replaced_string = i.replace(old,new)
        replaced_list.append(replaced_string)

    replaced_array= np.array(replaced_list)
    return replaced_array

In [94]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replacing_string(arr,'banana','fruit')

array(['apple', 'fruit', 'grape', 'pineapple'], dtype='<U9')

In [95]:
## Q59.
def concatenation(arr1,arr2):
    return np.concatenate((arr1,arr2))

In [96]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenation(arr1,arr2)

array(['Hello', 'World', 'Open', 'AI'], dtype='<U5')

In [97]:
## Q60.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [98]:
def find_len(arr):
    length = 0
    for i in arr:
        max_length = max(length,len(i))

    return max_length


In [99]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
find_len(arr)

9

In [100]:
## Q61.
arr = np.random.randint(1,1000,100)
arr

array([515, 811, 442,  62, 101,  24, 845,  30, 388,  24, 120, 982, 495,
       152, 493, 492, 338, 439, 982, 655, 195, 370, 141, 962, 933, 214,
       858,  41, 479, 196, 425, 114, 903, 774, 201, 874, 571, 939, 399,
       995, 191, 748, 372, 704, 894, 216, 807, 472, 419, 438, 634, 102,
       803, 117, 104, 806, 214,  35, 687,  87, 969, 905, 103, 497, 810,
       638, 649, 140, 628, 197, 632, 250, 655, 994, 752, 794, 247, 598,
       320, 408, 537, 793, 400,  57, 750, 957, 232, 394, 628, 972, 589,
       883,  13, 216, 699, 449,  62, 341, 906, 471])

In [101]:
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("varaince",np.var(arr))
print("standard deviation",np.std(arr))

mean: 493.59
median: 475.5
varaince 93035.66189999998
standard deviation 305.01747802380106


In [102]:
## Q62.
arr = np.random.randint(1,100,50)
arr

array([91,  7,  7, 58, 98, 42, 23, 16, 39, 49, 83, 79, 85, 61, 16, 38, 67,
       18, 34, 55, 57, 86, 96, 36, 23, 81, 10, 86, 47, 95, 65, 48, 71, 71,
       63, 41, 50, 37, 86, 15, 28, 27, 87, 80, 38,  4, 71, 54, 29,  4])

In [103]:
print("Percentile_25:",np.percentile(arr,25))
print("Percentile_75:",np.percentile(arr,75))

Percentile_25: 28.25
Percentile_75: 77.0


In [104]:
## Q63.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
np.corrcoef(arr1,arr2)

array([[ 1., -1.],
       [-1.,  1.]])

In [105]:
## Q64.
arr1 = np.random.randint(1,10,(3,2))
arr2 = np.random.randint(10,20,(2,3))
print("arr1\n",arr1)
print("arr2\n",arr2)
result = np.dot(arr1,arr2)
print("result:\n",result)

arr1
 [[2 5]
 [8 9]
 [2 4]]
arr2
 [[18 13 11]
 [11 11 12]]
result:
 [[ 91  81  82]
 [243 203 196]
 [ 80  70  70]]


In [106]:
## Q65.
arr = np.random.randint(10,1000,50)
arr

array([926, 864, 647, 646, 624, 344, 599, 522, 838, 676, 638,  26, 689,
       708, 284, 927,  63, 922, 192, 765, 970, 935, 965, 574, 663,  86,
       354, 907,  15, 488,  60, 341, 119, 216, 777,  49, 687, 983, 686,
       121, 473, 436, 966, 340, 224, 864, 722, 826, 507, 326])

In [107]:
print("percentile_10:",np.percentile(arr,10))
print("percentile_50:",np.percentile(arr,50))
print("percentile_90:",np.percentile(arr,90))
print("1st quartile:",np.percentile(arr,25))
print("3rd quartile:",np.percentile(arr,75))

percentile_10: 83.7
percentile_50: 631.0
percentile_90: 927.8
1st quartile: 329.5
3rd quartile: 813.75


In [108]:
## Q66.
def finding_index(arr,value):
    indices = np.where(arr == value)
    return indices

In [109]:
arr = np.array([10,20,30,40,50])
value = 30
finding_index(arr,value)

(array([2], dtype=int64),)

In [110]:
## Q67.
arr = np.random.randint(1,11,10)
arr

array([ 9,  4, 10,  1,  2,  9,  7,  1, 10, 10])

In [111]:
sorted_arr = np.sort(arr)
sorted_arr

array([ 1,  1,  2,  4,  7,  9,  9, 10, 10, 10])

In [112]:
## Q68.
arr = np.array([12,25,6,42,8,30])

In [113]:
element = arr[arr>20]
element

array([25, 42, 30])

In [114]:
## Q69.
arr = np.array([1, 5, 8, 12, 15])
element = arr[arr %3 == 0]
element

array([12, 15])

In [115]:
## Q70
arr = np.array([10, 20, 30, 40, 50])
element = arr[(arr>=20) & (arr<=40)]
element

array([20, 30, 40])

In [116]:
## Q71.
arr = np.array([1,2,3])
byte_order = arr.dtype.byteorder
byte_order

'='

In [117]:
## Q72.
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
print("Original array bytes:")
print(arr.tobytes())

arr.byteswap(inplace=True)

print("\nByte-swapped array:",arr)
print("Byte-swapped array bytes:")
print(arr.tobytes())

Original array: [1 2 3]
Original array bytes:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

Byte-swapped array: [16777216 33554432 50331648]
Byte-swapped array bytes:
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03'


In [118]:
## Q73.
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
print("Original array bytes:")
print(arr.tobytes())

swapped_arr = arr.newbyteorder()

print("\nByte-swapped array:",swapped_arr)
print("Byte-swapped array bytes:")
print(swapped_arr.tobytes())

print("\nOriginal array after byte swap:", arr)
print("Original array bytes after byte swap:")
print(arr.tobytes())

Original array: [1 2 3]
Original array bytes:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

Byte-swapped array: [16777216 33554432 50331648]
Byte-swapped array bytes:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

Original array after byte swap: [1 2 3]
Original array bytes after byte swap:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'


In [119]:
## Q74.
import numpy as np
import sys

# Create a NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Print original array and its bytes
print("\nOriginal array:", arr)
print("Original array bytes:")
print(arr.tobytes())

# Check system endianness
system_endianness = sys.byteorder
print("\nSystem endianness:", system_endianness)

# Swap byte order conditionally
if system_endianness == 'little':
    swapped_arr = arr.newbyteorder('>')
elif system_endianness == 'big':
    swapped_arr = arr.newbyteorder('<')

# Print byte-swapped array and its bytes
print("\nByte-swapped array:", swapped_arr)
print("Byte-swapped array bytes:")
print(swapped_arr.tobytes())

# Print original array to show it has not been modified
print("\nOriginal array after byte swap:", arr)
print("Original array bytes after byte swap:")
print(arr.tobytes())



Original array: [1 2 3]
Original array bytes:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

System endianness: little

Byte-swapped array: [16777216 33554432 50331648]
Byte-swapped array bytes:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

Original array after byte swap: [1 2 3]
Original array bytes after byte swap:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'


In [120]:
## Q75.
import numpy as np
import sys

# Create a NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Print original array and its bytes
print("Original array:", arr)
print("Original array bytes:")
print(arr.tobytes())

# Check system endianness
system_endianness = sys.byteorder
print("\nSystem endianness:", system_endianness)

# Check array's byte order
array_byteorder = arr.dtype.byteorder
print("\nArray byte order:", array_byteorder)

# Determine if byte swapping is necessary
# '=' means native byte order, '<' means little-endian, '>' means big-endian
if (system_endianness == 'little' and array_byteorder == '>') or \
   (system_endianness == 'big' and array_byteorder == '<'):
    print("\nByte swapping is necessary.")
    swapped_arr = arr.byteswap().newbyteorder()
    print("\nByte-swapped array:", swapped_arr)
    print("Byte-swapped array bytes:")
    print(swapped_arr.tobytes())
else:
    print("Byte swapping is not necessary.")

# Print original array to show it has not been modified
print("\nOriginal array after check:", arr)
print("Original array bytes after check:")
print(arr.tobytes())


Original array: [1 2 3]
Original array bytes:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

System endianness: little

Array byte order: =
Byte swapping is not necessary.

Original array after check: [1 2 3]
Original array bytes after check:
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'


In [121]:
## Q76.
a = np.array([3,5,2,6,8,4])
b = np.copy(a)
print(a)
print(b)

[3 5 2 6 8 4]
[3 5 2 6 8 4]


In [122]:
b[2]

2

In [123]:
b[2] = 9
b

array([3, 5, 9, 6, 8, 4])

In [124]:
a

array([3, 5, 2, 6, 8, 4])

No,modifying array b(copy_arr) doen't affect the 
a (arr1) 

In [125]:
## Q77.
matrix = np.random.randint(1,11,(3,3))
matrix

array([[2, 1, 4],
       [4, 8, 9],
       [7, 8, 4]])

In [126]:
view_slice = matrix[:2,:2]
view_slice

array([[2, 1],
       [4, 8]])

In [127]:
view_slice[1,1]

8

In [128]:
view_slice[1,1] = 17
view_slice

array([[ 2,  1],
       [ 4, 17]])

In [129]:
matrix

array([[ 2,  1,  4],
       [ 4, 17,  9],
       [ 7,  8,  4]])

yes,modfying a view slice affects the original array.

In [130]:
## Q78.
array_a = np.arange(1,13).reshape(4,3)
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
view_b = array_a[1:3,1:3]
view_b

array([[5, 6],
       [8, 9]])

In [132]:
view_b += 5
view_b

array([[10, 11],
       [13, 14]])

In [133]:
array_a

array([[ 1,  2,  3],
       [ 4, 10, 11],
       [ 7, 13, 14],
       [10, 11, 12]])

yes, modifying view_b alter the original array_a

In [134]:
## Q79.
orig_array = np.random.randint(1,9,(2,4))
orig_array

array([[6, 7, 8, 6],
       [8, 1, 8, 2]])

In [135]:
reshaped_view = orig_array.reshape(4,2)
reshaped_view

array([[6, 7],
       [8, 6],
       [8, 1],
       [8, 2]])

In [136]:
reshaped_view[1:2,:1]

array([[8]])

In [137]:
reshaped_view[1:2,:1] = 30
reshaped_view

array([[ 6,  7],
       [30,  6],
       [ 8,  1],
       [ 8,  2]])

In [138]:
orig_array

array([[ 6,  7, 30,  6],
       [ 8,  1,  8,  2]])

yes, it reflects the changes in "orig_array"

In [139]:
## Q80.
data = np.random.randint(1,21,(3,4))
data

array([[ 3, 19, 19, 17],
       [ 8, 20,  3,  7],
       [ 2,  9, 13,  6]])

In [140]:
data_copy = data[data>5].copy()
data_copy

array([19, 19, 17,  8, 20,  7,  9, 13,  6])

In [141]:
data_copy[3]

8

In [142]:
data_copy[3] = 94
data_copy

array([19, 19, 17, 94, 20,  7,  9, 13,  6])

In [143]:
data

array([[ 3, 19, 19, 17],
       [ 8, 20,  3,  7],
       [ 2,  9, 13,  6]])

modfying the data_copy doesn't affect the original data

In [144]:
## Q81.
A = np.matrix([3,2,5,2])
B = np.matrix([7,4,2,8])

In [145]:
A + B

matrix([[10,  6,  7, 10]])

In [146]:
A - B

matrix([[-4, -2,  3, -6]])

In [147]:
## Q82.
C = np.random.randint(1,11,(3,2))
D = np.random.randint(11,21,(2,4))

In [148]:
result = np.dot(C , D)
result

array([[ 73,  58,  88,  87],
       [168, 140, 208, 212],
       [ 53,  47,  68,  72]])

In [149]:
## Q83.
E = np.random.randint(1,11,(3,2))
E

array([[8, 9],
       [4, 8],
       [4, 9]])

In [150]:
transpose = E.T
transpose

array([[8, 4, 4],
       [9, 8, 9]])

In [151]:
## Q84.
F = np.random.randint(1,11,(3,3))
F

array([[ 2,  6, 10],
       [ 5,  9,  7],
       [ 9,  4,  6]])

In [152]:
determinant = np.linalg.det(F)
determinant

-360.00000000000006

In [153]:
## Q85.
G = np.random.randint(1,11,(3,3))
G

array([[ 2,  5,  4],
       [10,  4,  8],
       [ 7,  2,  4]])

In [154]:
determinant = np.linalg.det(G)
if determinant != 0:
    invese_G = np.linalg.inv(G)
    print("matrix G",G)
    print("inverse_G",invese_G)

else:
    print("Matrix G is singular and cannot ve inverted.")

matrix G [[ 2  5  4]
 [10  4  8]
 [ 7  2  4]]
inverse_G [[-2.22044605e-17 -2.50000000e-01  5.00000000e-01]
 [ 3.33333333e-01 -4.16666667e-01  5.00000000e-01]
 [-1.66666667e-01  6.45833333e-01 -8.75000000e-01]]
